// Автоматично винесено з server.js (Фаза 1 модуляризації, 2026-08-08). Чисті дані, без логіки.

const SEASON_COSMETICS = [
    { id: 'season_crown', slot: 'hat', name: 'Корона ухилянта сезону', emoji: '👑', seasonOnly: true, price: 0 },
    { id: 'season_shades', slot: 'face', name: 'Окуляри чемпіона', emoji: '🕶️', seasonOnly: true, price: 0 },
    { id: 'season_cape', slot: 'neck', name: 'Мантія непіймання', emoji: '🧥', seasonOnly: true, price: 0 },
];

const COSMETICS = [
    // Головні убори
    { id: 'cap', slot: 'hat', name: 'Кепка контрабандиста', emoji: '🧢', img: '/images/cosmetic-hat-cap.webp', price: 800 },
    { id: 'ushanka', slot: 'hat', name: 'Вушанка діда', emoji: '🪖', img: '/images/cosmetic-hat-ushanka.webp', price: 1200 },
    { id: 'strawhat', slot: 'hat', name: 'Дачний бриль', emoji: '👒', img: '/images/cosmetic-hat-strawhat.webp', price: 900 },
    { id: 'helmet', slot: 'hat', name: 'Каска "про всяк випадок"', emoji: '⛑️', img: '/images/cosmetic-hat-helmet.webp', price: 1800 },
    { id: 'tophat', slot: 'hat', name: 'Циліндр авторитету', emoji: '🎩', img: '/images/cosmetic-hat-tophat.webp', price: 2500 },
    { id: 'gradcap', slot: 'hat', name: 'Диплом "поважної причини"', emoji: '🎓', img: '/images/cosmetic-hat-gradcap.webp', price: 3000 },
    { id: 'crown', slot: 'hat', name: 'Корона Мажора', emoji: '👑', img: '/images/cosmetic-hat-crown.webp', price: 5000 },
    { id: 'bucket', slot: 'hat', name: 'Каска з відра', emoji: '🪣', img: '/images/cosmetic-hat-bucket.webp', price: 600 },
    { id: 'bush', slot: 'hat', name: 'Кущ-камуфляж', emoji: '🪴', img: '/images/cosmetic-hat-bush.webp', price: 1100 },
    { id: 'pumpkin', slot: 'hat', name: 'Гарбузовий шолом', emoji: '🎃', img: '/images/cosmetic-hat-pumpkin.webp', price: 1300 },
    { id: 'mushroom', slot: 'hat', name: 'Капелюх-гриб', emoji: '🍄', img: '/images/cosmetic-hat-mushroom.webp', price: 1000 },
    { id: 'sock_hat', slot: 'hat', name: 'Шкарпетка на голові', emoji: '🧦', price: 700 },
    { id: 'target', slot: 'hat', name: 'Мішень (для адреналіну)', emoji: '🎯', img: '/images/cosmetic-hat-target.webp', price: 2200 },
    { id: 'toiletpaper', slot: 'hat', name: 'Рулон замість шапки', emoji: '🧻', img: '/images/cosmetic-hat-toiletpaper.webp', price: 500 },
    { id: 'umbrella_hat', slot: 'hat', name: 'Капелюх-парасолька', emoji: '☂️', img: '/images/cosmetic-hat-umbrella.webp', price: 1400 },
    { id: 'coconut', slot: 'hat', name: 'Кокосовий шолом', emoji: '🥥', img: '/images/cosmetic-hat-coconut.webp', price: 1600 },
    { id: 'icecube', slot: 'hat', name: 'Крижаний компрес на голові', emoji: '🧊', img: '/images/cosmetic-hat-icecube.webp', price: 900 },
    // Маскування обличчя
    { id: 'glasses', slot: 'face', name: 'Ботанічні окуляри', emoji: '👓', img: '/images/cosmetic-face-glasses.webp', price: 600 },
    { id: 'clown', slot: 'face', name: 'Клоунський ніс', emoji: '🤡', img: '/images/cosmetic-face-clown.webp', price: 500 },
    { id: 'mask', slot: 'face', name: 'Медична довідка-маска', emoji: '😷', img: '/images/cosmetic-face-mask.webp', price: 700 },
    { id: 'sunglasses', slot: 'face', name: 'Чорні окуляри', emoji: '🕶️', img: '/images/cosmetic-face-sunglasses.webp', price: 1000 },
    { id: 'disguise', slot: 'face', name: 'Маскування (вуса+окуляри)', emoji: '🥸', img: '/images/cosmetic-face-disguise.webp', price: 1800 },
    { id: 'ninja', slot: 'face', name: 'Ніндзя-маскування', emoji: '🥷', img: '/images/cosmetic-face-ninja.webp', price: 2200 },
    { id: 'oni', slot: 'face', name: 'Маска чорта', emoji: '👹', img: '/images/cosmetic-face-oni.webp', price: 2000 },
    { id: 'tengu', slot: 'face', name: 'Маска гобліна', emoji: '👺', img: '/images/cosmetic-face-tengu.webp', price: 2000 },
    { id: 'skull', slot: 'face', name: 'Маска смерті', emoji: '💀', img: '/images/cosmetic-face-skull.webp', price: 2600 },
    { id: 'theater', slot: 'face', name: 'Театральна маска', emoji: '🎭', img: '/images/cosmetic-face-theater.webp', price: 1900 },
    { id: 'goggles', slot: 'face', name: 'Захисні окуляри', emoji: '🥽', img: '/images/cosmetic-face-goggles.webp', price: 1100 },
    { id: 'bear', slot: 'face', name: 'Маска ведмедя', emoji: '🐻', img: '/images/cosmetic-face-bear.webp', price: 1700 },
    { id: 'wolf', slot: 'face', name: 'Маска вовка', emoji: '🐺', img: '/images/cosmetic-face-wolf.webp', price: 1700 },
    { id: 'fox', slot: 'face', name: 'Маска лисиці', emoji: '🦊', img: '/images/cosmetic-face-fox.webp', price: 1700 },
    { id: 'boar', slot: 'face', name: 'Маска кабана', emoji: '🐗', img: '/images/cosmetic-face-boar.webp', price: 1700 },
    { id: 'pig', slot: 'face', name: 'Маска порося', emoji: '🐷', img: '/images/cosmetic-face-pig.webp', price: 1700 },
    // Аксесуар на шию
    { id: 'bowtie', slot: 'neck', name: 'Метелик "для солідності"', emoji: '🎀', img: '/images/cosmetic-neck-bowtie.webp', price: 700 },
    { id: 'scarf', slot: 'neck', name: 'Шарф ухилянта', emoji: '🧣', img: '/images/cosmetic-neck-scarf.webp', price: 900 },
    { id: 'tie', slot: 'neck', name: 'Діловий галстук', emoji: '👔', img: '/images/cosmetic-neck-tie.webp', price: 1500 },
    { id: 'medal', slot: 'neck', name: 'Медаль "За хоробрість втечі"', emoji: '🎖️', img: '/images/cosmetic-neck-medal.webp', price: 3500 },
    { id: 'chain', slot: 'neck', name: 'Золотий ланцюг авторитета', emoji: '🔗', price: 2400 },
    { id: 'beads', slot: 'neck', name: 'Чотки на удачу', emoji: '📿', price: 1300 },
    { id: 'sportmedal', slot: 'neck', name: 'Спортивна медаль', emoji: '🏅', price: 2000 },
    { id: 'goldmedal', slot: 'neck', name: 'Золота медаль чемпіона', emoji: '🥇', price: 3000 },
    { id: 'nazar', slot: 'neck', name: 'Амулет від зурочення', emoji: '🧿', price: 1600 },
    { id: 'gem', slot: 'neck', name: 'Діамантовий кулон', emoji: '💎', price: 4500 },
    { id: 'volunteer_ribbon', slot: 'neck', name: 'Волонтерська стрічка', emoji: '🎗️', price: 800 },
    { id: 'bell', slot: 'neck', name: 'Дзвіночок (як у кота)', emoji: '🔔', price: 600 },
    { id: 'headphones', slot: 'neck', name: 'Навушники на шиї', emoji: '🎧', price: 1900 },
    { id: 'bone', slot: 'neck', name: 'Кістка на шнурку', emoji: '🦴', price: 700 },
    // Рамки клікера (суцільне світіння) + дві анімовані
    { id: 'frame_red', slot: 'frame', name: 'Червона рамка небезпеки', color: '#c3073f', price: 1500 },
    { id: 'frame_gold', slot: 'frame', name: 'Золота рамка', color: '#ffd700', price: 2500 },
    { id: 'frame_neon', slot: 'frame', name: 'Неонова рамка', color: '#e0a52e', price: 2000 },
    { id: 'frame_pink', slot: 'frame', name: 'Рожева рамка', color: '#9c5330', price: 1800 },
    { id: 'frame_toxic', slot: 'frame', name: 'Токсична рамка', color: '#39ff14', price: 2000 },
    { id: 'frame_royal', slot: 'frame', name: 'Королівська рамка', color: '#9c27b0', price: 2800 },
    { id: 'frame_ice', slot: 'frame', name: 'Крижана рамка', color: '#7df9ff', price: 1700 },
    { id: 'frame_blood', slot: 'frame', name: 'Кривава рамка', color: '#8b0000', price: 1600 },
    { id: 'frame_lime', slot: 'frame', name: 'Лаймова рамка', color: '#ccff00', price: 1800 },
    { id: 'frame_amber', slot: 'frame', name: 'Бурштинова рамка', color: '#ffbf00', price: 1900 },
    { id: 'frame_violet', slot: 'frame', name: 'Фіолетова рамка', color: '#6a00ff', price: 2100 },
    { id: 'frame_white', slot: 'frame', name: 'Біла рамка', color: '#f5f5f5', price: 1500 },
    { id: 'frame_teal', slot: 'frame', name: "М'ятна рамка", color: '#00ffab', price: 1900 },
    { id: 'frame_magenta', slot: 'frame', name: 'Магентова рамка', color: '#d500f9', price: 2200 },
    { id: 'frame_steel', slot: 'frame', name: 'Сталева рамка', color: '#90a4ae', price: 1400 },
    { id: 'frame_rainbow', slot: 'frame', name: 'Веселкова рамка (анімована)', color: 'rainbow', price: 6000 },
    { id: 'frame_siren', slot: 'frame', name: 'Сирена (анімована)', color: 'siren', price: 5500 },
    // Сезонні нагороди живуть у тому ж каталозі, щоб їх бачив гардероб і кімната,
    // але позначені seasonOnly — магазин їх не показує, купити не можна.
    ...SEASON_COSMETICS,
];

module.exports = { SEASON_COSMETICS, COSMETICS };
